# Generated by Django 5.0.6 on 2024-07-25 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('summary', models.TextField(max_length=500)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('date_create', models.DateField(auto_now_add=True)),
                ('date_updat', models.DateField(auto_now=True)),
            ],
        ),
    ]
