# Generated by Django 5.0.6 on 2024-07-28 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
