# Generated by Django 5.0.6 on 2024-08-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_updat',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
